/*
 * ESI Meta Spec
 * ESI specs and miscellaneous routes
 *
 * OpenAPI spec version: 0.1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.31
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.EsiMetaSpec);
  }
}(this, function(expect, EsiMetaSpec) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new EsiMetaSpec.WebUIApi();
  });

  describe('(package)', function() {
    describe('WebUIApi', function() {
      describe('getDiffVersionAVersionB', function() {
        it('should call getDiffVersionAVersionB successfully', function(done) {
          // TODO: uncomment, update parameter values for getDiffVersionAVersionB call and complete the assertions
          /*
          var versionA = "versionA_example";
          var versionB = "versionB_example";
          var opts = {};
          opts.userAgent = "userAgent_example";
          opts.xUserAgent = "xUserAgent_example";
          opts.datasource = "tranquility";

          instance.getDiffVersionAVersionB(versionA, versionB, opts, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a('string');
            // expect(data).to.be(null);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('getUi', function() {
        it('should call getUi successfully', function(done) {
          // TODO: uncomment, update parameter values for getUi call and complete the assertions
          /*
          var opts = {};
          opts.userAgent = "userAgent_example";
          opts.xUserAgent = "xUserAgent_example";
          opts.datasource = "tranquility";
          opts.version = "latest";

          instance.getUi(opts, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a('string');
            // expect(data).to.be(null);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
    });
  });

}));
