/*
 * ESI Meta Spec
 * ESI specs and miscellaneous routes
 *
 * OpenAPI spec version: 0.1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.31
 *
 * Do not edit the class manually.
 *
 */

(function(factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/GetStatusItem', 'model/GetVerifyOk', 'api/MetaApi', 'api/SwaggerApi', 'api/WebUIApi'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('./ApiClient'), require('./model/GetStatusItem'), require('./model/GetVerifyOk'), require('./api/MetaApi'), require('./api/SwaggerApi'), require('./api/WebUIApi'));
  }
}(function(ApiClient, GetStatusItem, GetVerifyOk, MetaApi, SwaggerApi, WebUIApi) {
  'use strict';

  /**
   * ESI_specs_and_miscellaneous_routes.<br>
   * The <code>index</code> module provides access to constructors for all the classes which comprise the public API.
   * <p>
   * An AMD (recommended!) or CommonJS application will generally do something equivalent to the following:
   * <pre>
   * var EsiMetaSpec = require('index'); // See note below*.
   * var xxxSvc = new EsiMetaSpec.XxxApi(); // Allocate the API class we're going to use.
   * var yyyModel = new EsiMetaSpec.Yyy(); // Construct a model instance.
   * yyyModel.someProperty = 'someValue';
   * ...
   * var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
   * ...
   * </pre>
   * <em>*NOTE: For a top-level AMD script, use require(['index'], function(){...})
   * and put the application logic within the callback function.</em>
   * </p>
   * <p>
   * A non-AMD browser application (discouraged) might do something like this:
   * <pre>
   * var xxxSvc = new EsiMetaSpec.XxxApi(); // Allocate the API class we're going to use.
   * var yyy = new EsiMetaSpec.Yyy(); // Construct a model instance.
   * yyyModel.someProperty = 'someValue';
   * ...
   * var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
   * ...
   * </pre>
   * </p>
   * @module index
   * @version 0.1
   */
  var exports = {
    /**
     * The ApiClient constructor.
     * @property {module:ApiClient}
     */
    ApiClient: ApiClient,
    /**
     * The GetStatusItem model constructor.
     * @property {module:model/GetStatusItem}
     */
    GetStatusItem: GetStatusItem,
    /**
     * The GetVerifyOk model constructor.
     * @property {module:model/GetVerifyOk}
     */
    GetVerifyOk: GetVerifyOk,
    /**
     * The MetaApi service constructor.
     * @property {module:api/MetaApi}
     */
    MetaApi: MetaApi,
    /**
     * The SwaggerApi service constructor.
     * @property {module:api/SwaggerApi}
     */
    SwaggerApi: SwaggerApi,
    /**
     * The WebUIApi service constructor.
     * @property {module:api/WebUIApi}
     */
    WebUIApi: WebUIApi
  };

  return exports;
}));
